filebeat.prospectors:
- input_type: log
  paths:
  - /mydata/apache-tomcat-7.0.55/logs/catalina.out
  - /mydata/apache-tomcat-7.0.55/logs/cfniuerror.log
  - /mydata/apache-tomcat-7.0.55/logs/cfniuRegMonitor.log
  - /mydata/apache-tomcat-7.0.55/logs/cfniutrade2.0.log
  - /mydata/apache-tomcat-7.0.55/logs/cfniutrade3.0.log
  - /mydata/apache-tomcat-7.0.55/logs/cfniuwarn.log
  - /mydata/apache-tomcat-7.0.55/logs/localhost.*
  - /mydata/apache-tomcat-7.0.55/logs/localhost_access_log.*
  - /mydata/apache-tomcat-7.0.55/logs/manager.*
  tags: tomcat
- input_type: log
  paths:
  - /var/log/nginx/*.log
  tags: nginx
output.logstash:
  hosts: ["192.168.1.1:5043"]
name: "cfniu_156"



#elk服务器地址192.168.1.1