---
- name: install node
  hosts: node
  remote_user: root
  vars:
  - node: node-v8.9.0-linux-x64
  - jdk: jdk1.8.0_121
  tasks:
      - name: check dir exist
        file: path=/mydata state=directory
      - name: copy node to client        
        copy: src=./{{ node }}.tar.gz dest=/mydata/
      - name: copy jdk to client
        copy: src=./{{ jdk }}.tar.gz dest=/mydata/
      - name: install node&jdk
        shell: cd /mydata; tar -xzf {{ node }}.tar.gz;tar -xzf {{ jdk }}.tar.gz; 
      - name: change profile
        shell: echo -e "JAVA_HOME=/mydata/{{ jdk }}\nCLASSPATH=\$JAVA_HOME/lib/\nNODE_HOME=/mydata/{{ node }}\nPATH=\$PATH:\$JAVA_HOME/bin:\$NODE_HOME/bin:\nexport PATH JAVA_HOME NODE_HOME CLASSPATH">>/etc/profile; source /etc/profile
